### PR TITLE
fix: rectify sendSignedTransaction

### LINKED ISSUE #108: rectify sendSignedTransaction helper
- get rid of `await`. We are not using async/await in leap-core 🧐
- add it to `index.d.ts` typedefs

The helper was introduced in #101 as a workaround for fast sell to wait on tx receipt.

### PR DESCRIPTION
**Pull request by troggy**
- got rid of `async/await` 
- supporting Ethers.js. Detect if provided plasma object is Web3 or JSONRPCProvider of Ethers.
- added `sendSignedTransaction` to typedefs. Without a proper return type for now — need to add Ethers.js typedefs for that
- use proper timeout-loop: the previous one did nothing for async code

Resolves #108 

Veried for Ethers here: https://github.com/leapdao/leap-guardian/pull/12
Haven't verified for Web3 yet

### CODE REVIEW

File: lib/helpers.js [hunk 1]
```diff
@@ -268,45 +268,59 @@ export function getProof(plasma, tx, slotId, validatorAddr) {
...
-          return reject(err);
-        }
-        return resolve(res);
-      }
-    );
-  }).then(async ({ result }) => {
-    let receipt;
-    let rounds = 50;
+const awaitForReceipt = (txHash, promise, plasma, round) => {
+  if (round >= 50) return Promise.resolve();
```
Comment (sunify) [inline lib/helpers.js]: Why resolve, not reject?
